= {{{upperCaseType}}}

Before you can build something using `{{{upperCaseType}}}`, you have to understand {{{lowerCaseType}}} toolkit.  Based on books, research, and trial and error, the best approach I have found is link:http://jsfiddle.net/[js fiddle].
If I am unfamiliar with or (simply) don’t understand a specific piece of the framework, then step one is to build and
publish a fiddle (or fiddles) until it makes sense.  This directory is dedicated to exploration of this framework.
The `fiddle.sh` script can be used to extend or test drive this collection. The following table outlines how.

=== fiddle.sh {{{upperCaseType}}} Command Examples

[cols="2,2,5a"]
|===
|Create
|`./fiddle.sh "create" "{{{lowerCaseType}}}" "fiddle-0000-Template"`
|link:create.md[sample output]
|Delete
|`./fiddle.sh "delete" "{{{lowerCaseType}}}" "0000"`
|link:delete.md[sample output]
|Fork
|`./fiddle.sh "fork" "{{{lowerCaseType}}}" "0000" "fiddle-0001-Fork"`
|link:fork.md[sample output]
|Index
|`./fiddle.sh "index" "{{{lowerCaseType}}}"`
|link:index.md[sample output]
|List
|`./fiddle.sh "list" "{{{lowerCaseType}}}"`
|link:list.md[sample output]
|Refactor
|`./fiddle.sh "refactor" "{{{lowerCaseType}}}" "0000" "fiddle-0100-Refactor"`
|link:refactor.md[sample output]
|Start
|`./fiddle.sh "start" "{{{lowerCaseType}}}"`
|link:start.md[sample output]
|===
