= ExtJS 6

Before you can build a website using ExtJS, you have to understand ExtJS.  Based on books, research, and trial and
error, the best approach I have found is link:https://fiddle.sencha.com/#home[Sencha Fiddle].  If I am unfamiliar with or
(simply) don’t understand a specific piece of the framework, then step one is to build and publish a fiddle (or fiddles)
until it makes sense.  This directory is dedicated to exploration of this framework.  The `fiddle.sh` script can be used
to extend or test drive this collection. The following table outlines how.

=== fiddle.sh ExtJS 6 Command Examples

[cols="2,2,5a"]
|===
|Create
|`./fiddle.sh "create" "extjs6" "fiddle-0000-Template"`
|link:create.md[sample output & additional details]
|Delete
|`./fiddle.sh "delete" "extjs6" "0000"`
|link:delete.md[sample output & additional details]
|Fork
|`./fiddle.sh "fork" "extjs6" "0000" "fiddle-0001-Fork"`
|link:fork.md[sample output & additional details]
|Index
|`./fiddle.sh "index" "extjs6"`
|link:index.md[sample output & additional details]
|List
|`./fiddle.sh "list" "extjs6"`
|link:list.md[sample output & additional details]
|Refactor
|`./fiddle.sh "refactor" "extjs6" "0000" "fiddle-0100-Refactor"`
|link:refactor.md[sample output & additional details]
|Start
|`./fiddle.sh "start" "extjs6"`
|link:start.md[sample output & additional details]
|===
