= ExtJS 6

Before you can build a website using ExtJS, you have to understand ExtJS.  Based on books, research, and trial and
error, the best approach I have found is link:https://fiddle.sencha.com/#home[Sencha Fiddle].  If I am unfamiliar with or
(simply) don’t understand a specific piece of the framework, then step one is to build and publish a fiddle (or fiddles)
until it makes sense.  This directory is dedicated to exploration of this framework.  The `fiddle.sh` script can be used
to extend or test drive this collection. The following table outlines how.

== Installation

Complete the link:https://github.com/bradyhouse/house/wiki/Setup-(Mac-OS)[Setup (Mac OS)] procedure. Open a terminal
window and run the command `fiddle setup mac js-beautify`. The setup command simply installs js-beautify, which
is required by the combine command (see below).


=== fiddle.sh ExtJS 6 Commands

[cols="2,2,5a"]
|===
|Create
|`fiddle "create" "extjs6" "fiddle-0000-Template"`
|link:create.md[sample output & additional details]
|Combine
|`fiddle "combine" "extjs6" "0000"`
|link:combine.md[sample output & additional details]
|Delete
|`fiddle "delete" "extjs6" "0000"`
|link:delete.md[sample output & additional details]
|Fork
|`fiddle "fork" "extjs6" "0000" "fiddle-0001-Fork"`
|link:fork.md[sample output & additional details]
|Index
|`fiddle "index" "extjs6"`
|link:index.md[sample output & additional details]
|List
|`fiddle "list" "extjs6"`
|link:list.md[sample output & additional details]
|Refactor
|`fiddle "refactor" "extjs6" "0000" "fiddle-0100-Refactor"`
|link:refactor.md[sample output & additional details]
|Start
|`fiddle "start" "extjs6"`
|link:start.md[sample output & additional details]
|===

== Online Resources

* link:https://cdnjs.com/libraries/extjs[CloudFlare CDN Libraries]
