= Amazon Web Services

I finally finished my bachelor's degree in 2015.  At 40 I graduated Cum Laude from the Illinois Institute of
Technology's Information and Technology Management program.  The achievement took nearly eight years of
my life, cost nearly 80K.  In hind sight, I wish I would have just spent that time (and money) studying and
mastering AWS.  Anyway, life goes on and here we are--time to make-up for lost time. This directory is
dedicated to my notes and `fiddles` involving AWS.  At the outset, this just means markdown files written
while watching lectures on link:http://acloud.guru[acloud.guru].


== Lecture Notes

[cols=">s,m", width="100%"]
|=========================================================
2+>| **Intro**
||link:overview.md[10,000 Foot Overview]
||link:dont-freakout.md[Don't Freakout]
2+>| **IAM**
||link:iam.md[IAM 101]
||link:billing-alarm.md[Creating a Billing Alarm]
2+>| **S3**
||link:s3.md[S3 101]
||link:s3-versioning.md[S3 Versioning]
||link:s3-lifecycle.md[Life Cycle Management]
||link:s3-encryption.md[Encryption]
2+>| **CloudFront**
||link:cloudfront-intro.md[CloudFront 101]
||link:cloudfront-create-a-cdn.md[Create a Distribution]
2+>| **Storage Gateway**
||link:storage-gateway.md[Storage Gateway 101]
|=========================================================
