---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos65
    driver:
     box: learningchef/centos65
     box_url: learningchef/centos65

suites:
  - name: default
    run_list:
      - recipe[fiddle-0000-Template::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
