---
swagger: "2.0"
info:
  description: "Mock API"
  version: "1.0.0"
  title: "Canvas Mock API"
basePath: "/api/v1/"
schemes:
- "http"
paths:
  /pages:
    post:
      tags:
        - pages
      summary: "Get paged data."
      description: "Get paged data."
      parameters:
        - in: body
          name: pagedRequest.
          description: Paged data input parameters.
          schema:
            type: object
            required:
              - pageNumber
            properties:
              pageNumber:
                type: number
              searchCriteria:
                type: object
      operationId: "pagesPOST"
      responses:
        200:
          description: "successful operation"
        500:
          description: "Internal Server error"
      x-swagger-router-controller: "PagesController"  
definitions: {}
