= Chef

In 2018, I passed the AWS Certified Solutions Architect - Associate Exam.  Afterwards, I found myself left with
one big question: _Now what?_ I mean how do you "fiddle" with the cloud?  Well, you need a way to configure and
test infrastructure (aka AWS stuff) using code. link:https://www.chef.io/[Chef] is a framework for
doing that.  This collection (aka directory, aka _barrel_) is aimed at gaining some experience
with using this framework.


== Installation

On Mac OS X, open a terminal window and run the command `fiddle setup mac chef`. The setup command installs:

* virtualbox
* vagrant
* vagrant-manager
* chefdk
  ** chef
  ** chef client suite
  ** berkshire
  ** kitchen

After installing these packages, it then uses `kitchen init` to configure the link:kitchen[kitchen directory] based
on the CHEF_* environment variables specified in the link:../../scripts/bin/_env.sh[_env.sh] script.

NOTE - Your machine should be configured with homebrew.  In addition, should complete the fiddle.sh Bash setup
procedure.


== fiddle.sh Chef Commands

[cols="2,2,5a"]
|===
|Create
|`fiddle "create" "chef" "fiddle-0000-Template"`
|link:create.md[sample output & additional details]
|Delete
|`fiddle "delete" "chef" "0000"`
|link:delete.md[sample output & additional details]
|List
|`fiddle "list" "chef"`
|link:list.md[sample output & additional details]
|Start
|`fiddle "start" "chef" "0000"`
|link:start.md[sample output & additional details]
|===


== Online Resources

*   link:https://github.com/chef/chef-dk[Chef Development Kit Github Repo]
*   link:http://www.learningchef.com[Learning Chef]
*   link:http://docs.chef.io[Chef Documentation]

