module.exports = {
  'csv'     : 'text/csv',
  'js'      : 'text/javascript',
  'ts'      : 'text/typescript',
  'json'    : 'text/json',
  'txt'     : 'text/plain',
  'adoc'    : 'text/plain',
  'md'      : 'text/x-markdown',
  'markdown': 'text/x-markdown',
  'htm'     : 'text/html',
  'html'    : 'text/html',
  'css'     : 'text/css',
  'tag'     : 'text/html',
  'ico'     : 'image/x-icon',
  'png'     : 'image/png',
  'svg'     : 'image/svg+xml',
  'sql'     : 'text/sql',
  'cer'     : 'text/cer',
  'zip'     : 'application/zip',
  'pdf'     : 'application/pdf',
  'xlsx'    : 'application/zip',
  'bmpr'    : 'application/octet-stream',
  'dmg'     : 'application/octet-stream',
  'webloc'  : 'application/xml',
  'docx'    : 'application/zip'
}
