= Node

Node.js is a way around the pain and suffering required to implement a web service using Java
or .NET. Using Node.js, a developer can create a web service and consuming client application
using pure JavaScript. As per the source of all knowledge:  “Node.js is an open source,
cross-platform runtime environment for server-side and networking applications. Node.js
applications are written in JavaScript, and can be run within the Node.js runtime on OS X,
Microsoft Windows, Linux, FreeBSD, NonStop and PCs … Node.js contains a built-in library
to allow applications to act as a Web server without software such as Apache HTTP Server or
IIS (Node.js, Wikipedia).”

In other words, if you are an aspiring web developer trying to decide on a platform (.NET, PHP, 
Java, Ruby), then Node.js is the writing the wall.  The answer is JavaScript. Pre-_Node.js_, 
JavaScript was seen as purely a necessary frontend evil.  It could be used to do cool things in 
the web browser, but it was beholding to the backend for the heavy lifting.  The web server and 
database tiers were beyond its reach. Node.js breaks this paradigm. Now JavaScript can be used for 
doing cool things on the backend as well. 

This directory is dedicated to exploration of this framework.  The `fiddle.sh` script can be used 
to extend or test drive this collection. The following table outlines how.

=== fiddle.sh Node Commands

[cols="2,2,5a"]
|===
|Create
|`./fiddle.sh "create" "node" "fiddle-0000-Template"`
|link:create.md[sample output & additional details]
|Delete
|`./fiddle.sh "delete" "node" "0000"`
|link:delete.md[sample output & additional details]
|Fork
|`./fiddle.sh "fork" "node" "0000" "fiddle-0001-Fork"`
|link:fork.md[sample output & additional details]
|List
|`./fiddle.sh "list" "node"`
|link:list.md[sample output & additional details]
|Refactor
|`./fiddle.sh "refactor" "node" "0000" "fiddle-0100-Refactor"`
|link:refactor.md[sample output & additional details]
|Start
|`./fiddle.sh "start" "node"`
|link:start.md[sample output & additional details]
|===


== Kindle Injection

As a starting point, I will be working through Jim R. Wilson book link:https://pragprog.com/book/jwnode/node-js-the-right-way[Node.js the Right Way].


== Online Resources

*   link:http://nodejs.org[nodejs.org]
*   link:http://nodejs.org/api[node api]
**  link:http://nodejs.org/api/fs.html[fs]
**  link:http://nodejs.org/api/child_process.html[child_process]
**  link:http://nodejs.org/api/events.html[events]
**  link:http://nodejs.org/api/buffer.html[buffer]
*   link:http://json.org[json.org]
*   link:https://github.com/jimbojw/right-way[jimbojw > right-way]
