= Dojo

Before you can build a website using the link:http://dojotoolkit.org/api/[Dojo toolkit], you have to understand the
toolkit.  Based on books, research, and trial and error, the best approach I have found is link:http://jsfiddle.net/[js fiddle].
If I am unfamiliar with or (simply) don’t understand a specific piece of the framework, then step one is to build and
publish a fiddle (or fiddles) until it makes sense.  This directory is dedicated to exploration of this framework.
The `fiddle.sh` script can be used to extend or test drive this collection. The following table outlines how.

=== fiddle.sh Dojo Commands

[cols="2,2,5a"]
|===
|Create
|`./fiddle.sh "create" "dojo" "fiddle-0000-Template"`
|link:create.md[sample output & additional details]
|Delete
|`./fiddle.sh "delete" "dojo" "0000"`
|link:delete.md[sample output & additional details]
|Fork
|`./fiddle.sh "fork" "dojo" "0000" "fiddle-0001-Fork"`
|link:fork.md[sample output & additional details]
|Index
|`./fiddle.sh "index" "dojo"`
|link:index.md[sample output & additional details]
|List
|`./fiddle.sh "list" "dojo"`
|link:list.md[sample output & additional details]
|Refactor
|`./fiddle.sh "refactor" "dojo" "0000" "fiddle-0100-Refactor"`
|link:refactor.md[sample output & additional details]
|Start
|`./fiddle.sh "start" "dojo"`
|link:start.md[sample output & additional details]
|===
