= C

Native iphone apps are written in Objective C.  Objective C is a _superset_ of C. And so, if you want to build iphone apps, you
should probably begin with C.  This directory is dedicated to fiddles involving C.  The `fiddle.sh` script can be  used to extend or test drive this collection. The following table outlines how.

=== fiddle.sh C Commands

[cols="2,2,5a"]
|===
|Create
|`./fiddle.sh "create" "c" "fiddle-0000-Template"`
|link:create.md[sample output & additional details]
|Fork
|`./fiddle.sh "fork" "c" "0000" "fiddle-0003-TemplateFork"`
|link:fork.md[sample output & additional details]
|Delete
|`./fiddle.sh "delete" "c" "0000"`
|link:delete.md[sample output & additional details]
|Refactor
|`./fiddle.sh "refactor" "c" "0000" "fiddle-0100-Refactor"`
|link:refactor.md[sample output & additional details]
|List
|`./fiddle.sh "list" "c"`
|link:list.md[sample output & additional details]
|===


== Kindle Injection

As a starting point, I will work through the examples outlined by Stephen Kochan in the book link:http://a.co/1QJ9MDN[Programming in C (Developer's Library) 4th Edition].


