
chr.driverPath=chromedriver
chr.targetUrl=https://amazon.com
chr.ur=
chr.ps=
chr.isHeadless=false
# Session Time in Miliseconds
# 1 hour = 3600000 ms
chr.sessionDuration=3600000
chr.jsFile=session.js
chr.cookie.name=testing
chr.cookie.value=
chr.cookie.domain=
chr.cookie.path=
chr.cookie.isSecure=true
chr.login.urFieldId=user
chr.login.psFieldId=pwd
chr.login.btnId=loginBtn

