= RxJS

This directory is dedicated to fiddles involving my exploration of the link:https://github.com/Reactive-Extensions/RxJS[Reactive Extensions for JavaScript (RxJS)].  
For DOM manipulation (and further practise), these fiddles utilize d3.  The template index.html file includes a 
reference to the link:https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.16/d3.js[3.5.16 version of d3 published on cdnjs].
For fiddles exclusively involving d3, checkout my link:../../d3[d3 fiddle collection].  This directory is dedicated to 
exploration of this framework.  The `fiddle.sh` script can be used to extend or test drive this collection. The following table outlines how.
                                                                                        
=== fiddle.sh RxJS Commands

[cols="2,2,5a"]
|===
|Create
|`./fiddle.sh "create" "rxjs" "fiddle-0000-Template"`
|link:create.md[sample output & additional details]
|Delete
|`./fiddle.sh "delete" "rxjs" "0000"`
|link:delete.md[sample output & additional details]
|Fork
|`./fiddle.sh "fork" "rxjs" "0000" "fiddle-0001-Fork"`
|link:fork.md[sample output & additional details]
|Index
|`./fiddle.sh "index" "rxjs"`
|link:index.md[sample output & additional details]
|List
|`./fiddle.sh "list" "rxjs"`
|link:list.md[sample output & additional details]
|Refactor
|`./fiddle.sh "refactor" "rxjs" "0000" "fiddle-0100-Refactor"`
|link:refactor.md[sample output & additional details]
|Start
|`./fiddle.sh "start" "rxjs"`
|link:start.md[sample output & additional details]
|===
