= RxJS

This directory is dedicated to fiddles involving my exploration of the link:https://github.com/Reactive-Extensions/RxJS[Reactive Extensions for JavaScript (RxJS)].
For DOM manipulation (and further practise), these fiddles utilize d3.  The template index.html file includes a
reference to the link:https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.16/d3.js[3.5.16 version of d3 published on cdnjs].
For fiddles exclusively involving d3, checkout my link:../../d3[d3 fiddle collection].  This directory is dedicated to
exploration of this framework.  The `fiddle.sh` script can be used to extend or test drive this collection. The following table outlines how.

=== fiddle.sh RxJS Commands

[cols="2,2,5a"]
|===
|Create
|`./fiddle.sh "create" "rxjs" "fiddle-0000-Template"`
|link:create.md[sample output & additional details]
|Delete
|`./fiddle.sh "delete" "rxjs" "0000"`
|link:delete.md[sample output & additional details]
|Fork
|`./fiddle.sh "fork" "rxjs" "0000" "fiddle-0001-Fork"`
|link:fork.md[sample output & additional details]
|Index
|`./fiddle.sh "index" "rxjs"`
|link:index.md[sample output & additional details]
|List
|`./fiddle.sh "list" "rxjs"`
|link:list.md[sample output & additional details]
|Refactor
|`./fiddle.sh "refactor" "rxjs" "0000" "fiddle-0100-Refactor"`
|link:refactor.md[sample output & additional details]
|Start
|`./fiddle.sh "start" "rxjs"`
|link:start.md[sample output & additional details]
|===

== Kindle Injection

As a starting point, I will work through the examples outlined by Sergi Mansilla in the book link:http://a.co/au0EOZC[Reactive Programming with RxJS: Untangle Your Asynchronous JavaScript Code].

Note, the example source code can be downloaded from the publisher's website, link:https://pragprog.com/titles/smreactjs/source_code[The Pramatic Bookshelf].

== Online Resources

*   link:https://github.com/Reactive-Extensions/RxJS[github > reactive-extensions > RxJS]
*   link:http://reactivex.io/documentation[ReactiveX Documentation]
**  link:http://reactivex.io/documentation/operators.html[Operators]
**  link:http://reactivex.io/documentation/observable.html[Observables]
**  link:http://reactivex.io/documentation/single.html[Single]
**  link:http://reactivex.io/documentation/subject.html[Subject]
**  link:http://reactivex.io/documentation/scheduler.html[Scheduler]
*   link:http://rxmarbles.com/[RxMarbles]




\
