= PHP

Before you can build a website using the Personal Home Page (PHP) language, you have to understand PHP.  
Based on books, research, and trial and error, the best approach I have found is to _fiddle_.  If I am unfamiliar 
with or (simply) don’t understand a specific piece of the language, then step one is to build a fiddle (or fiddles) 
until it makes sense.  This directory is dedicated to exploration of this framework.  The `fiddle.sh` script can be used
to extend or test drive this collection. The following table outlines how.

=== fiddle.sh PHP Commands

[cols="2,2,5a"]
|===
|Create
|`./fiddle.sh "create" "php" "fiddle-0000-Template"`
|link:create.md[sample output & additional details]
|Delete
|`./fiddle.sh "delete" "php" "0000"`
|link:delete.md[sample output & additional details]
|Fork
|`./fiddle.sh "fork" "php" "0000" "fiddle-0001-Fork"`
|link:fork.md[sample output & additional details]
|List
|`./fiddle.sh "list" "php"`
|link:list.md[sample output & additional details]
|Refactor
|`./fiddle.sh "refactor" "php" "0000" "fiddle-0100-Refactor"`
|link:refactor.md[sample output & additional details]
|===




