name 'fiddle-0001-ChefServer'
maintainer 'Brady House'
maintainer_email 'bradyhouse@gmail.com'
license 'All Rights Reserved'
description 'Installs/Configures fiddle-0001-ChefServer'
long_description 'Installs/Configures fiddle-0001-ChefServer'
version '0.1.0'
chef_version '>= 13.0'
issues_url 'https://github.com/bradyhouse/house/issues'
source_url 'https://github.com/bradyhouse/house'
