---
driver:
  name: {{DriverName}}

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: {{PlatformName}}
    driver:
     box: {{PlatformDriverBox}}
     box_url: {{PlatformDriverBoxUrl}}

suites:
  - name: default
    run_list:
      - recipe[{{FiddleName}}::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
