name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Latest React Fiddle
      working-directory: fiddles/react/fiddle-0017-EnterpriseAgGrid
      run: npm install
      
    - name: Install Latest Angular Cli Fiddle
      working-directory: fiddles/angular2-cli/fiddle-0040-CSVReporter
      run: npm install
